version: '3'

services:

  database:
    image: mysql:latest
    container_name: tododb
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: SPRING_DB
    ports:
        - 3307:3306

  backend:
    image: todo:backend
    container_name: todobackend
    build:
        context: ./back-end
        dockerfile: Dockerfile
    ports:
        - 8081:8080
    environment:
        MYSQL_HOST: database
    depends_on:
        - database
  
  frontend:
    image: todo:front
    container_naem: todofrontend
    build:
        context: ./front-end
        dockerfile: Dockerfile
    ports:
        - 4444:80
    depends_on:
        - database
        - backend
