version: '3'

services:

  database:
    image: mysql:latest
    container_name: tododb
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: SPRING_DB
    ports:
        - 3306:3306
    restart: always
    networks:
        - db-network

  backend:
    image: todo:backend
    container_name: todobackend
    build:
        context: ./back-end
        dockerfile: Dockerfile
    ports:
        - 8080:8080
    environment:
        MYSQL_HOST: database
    depends_on:
        - database
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
        - app-network
        - db-network
  
  frontend:
    image: todo:front
    container_name: todofrontend
    build:
        context: ./front_end
        dockerfile: Dockerfile
    ports:
        - 4444:80
    networks:
        - app-network
    depends_on:
        - database
        - backend

networks:
    app-network:
    db-network: