version: '3'

services:

  database:
    image: mysql:latest
    container_name: tododb
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_DATABASE: SPRING_DB
    ports:
        - 3306:3306
    restart: always


  backend:
    image: todo:backend
    container_name: backend
    build:
        context: ./back-end
        dockerfile: Dockerfile
    ports:
        - 8080:8080
    environment:
        MYSQL_HOST: database
    depends_on:
        - database
  
  frontend:
    image: todo:front
    container_name: todofrontend
    build:
        context: ./front_end
        dockerfile: Dockerfile
        args:
            REACT_APP_PROD_API: /api
    ports:
        - 80:80
    depends_on:
        - backend